(in-package :indras-pearls)

(defun draw-circle (x y r &optional (draw-fn #'vecto:stroke))
  (vecto:centered-circle-path x y r)
  (funcall draw-fn))

(defun plot-circle (circle color &optional (k 1))
  (let* ((cen (circle-cen circle))
	 (rad (circle-rad circle))
	 (x   (realpart cen))
	 (y   (imagpart cen)))
    (vecto:set-rgb-fill (nth 0 color)
			(nth 1 color)
			(nth 2 color))
    (draw-circle (* k x) (* k y) (* k rad) #'vecto:fill-path)))

(defun hexagon (sf x0 y0)
  (let ((X '(3/2 0 -3/2 -3/2 0 3/2 3/2))
	(Y (mapcar (lambda (x) (* (sqrt 3) x)) '(1/2 1 1/2 -1/2 -1 -1/2 1/2 1/2))))
    (vecto:move-to (+ (* sf (first X)) x0) 
		   (+ (* sf (first Y)) y0))
    (mapc (lambda (x y)
	    (vecto:line-to (+ (* sf x) x0) 
			   (+ (* sf y) y0))) 
	  (rest X) (rest Y)))
  (vecto:stroke))
